name: ci

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  ci:
    uses: bboe/.github/.github/workflows/python-ci.yml@main
    with:
      lint: false
      test-group: dev
      locked: true
      os: '["ubuntu-latest", "macos-latest"]'
      pytest-args: "-q"
